version: "3.7"

services:
  go:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./.env:/.env
    ports:
      - 1323:80

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5675:5675
      - 15675:15675
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  db-data:
  rabbitmq-data: